name: Simple Push to VPS (with Artisan Clear)

on:
  push:
    branches: [ main ]     # change if needed
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Prune CI files
        run: |
          rm -rf .git .github

      - name: Upload Project to VPS (Password Auth)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          source: "."
          target: "/var/www/devajayantha"
          overwrite: true
          rm: false
          strip_components: 0

